#!/usr/bin/env sh
# Base1 preview provenance verifier.
#
# Read-only verifier for preview bundle SHA256SUMS generated by
# scripts/base1-preview-provenance.sh. It does not regenerate provenance,
# launch QEMU, install Base1, write devices, create images, or claim Base1 is
# bootable.

set -eu

BUNDLE_DIR=${BASE1_EMULATOR_BUNDLE:-build/base1-emulator-preview}
SUMS_REL=reports/SHA256SUMS
STATUS=pass
CHECKED=0

usage() {
  cat <<'USAGE'
base1 preview verifier

usage:
  scripts/base1-preview-verify.sh [options]

options:
  --bundle <dir>   Base1 emulator preview bundle directory under build/
  -h, --help       show this help

input:
  <bundle>/reports/SHA256SUMS

checks:
  bundle is under build/
  SHA256SUMS exists
  each listed file exists
  each listed file hash matches the recorded SHA-256

non-claims:
  This verifier is read-only. It does not launch the emulator, install Base1,
  create an image, validate hardware, complete recovery, or prove that Base1 is
  bootable. It does not claim Base1 is bootable.
USAGE
}

fail() {
  printf 'base1 preview verifier: %s\n' "$1" >&2
  exit 1
}

pass_check() {
  printf 'PASS  %s\n' "$1"
}

fail_check() {
  printf 'FAIL  %s\n' "$1"
  STATUS=failed
}

have() {
  command -v "$1" >/dev/null 2>&1
}

hash_file() {
  file=$1
  if have shasum; then
    shasum -a 256 "$file" | awk '{print $1}'
  elif have sha256sum; then
    sha256sum "$file" | awk '{print $1}'
  elif have openssl; then
    openssl dgst -sha256 "$file" | awk '{print $NF}'
  else
    fail 'no SHA-256 tool found: need shasum, sha256sum, or openssl'
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bundle)
      [ "$#" -ge 2 ] || fail '--bundle requires a value'
      BUNDLE_DIR=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

case "$BUNDLE_DIR" in
  build/*) ;;
  *) fail "bundle must be under build/: $BUNDLE_DIR" ;;
esac

[ -d "$BUNDLE_DIR" ] || fail "bundle directory does not exist: $BUNDLE_DIR"
SUMS="$BUNDLE_DIR/$SUMS_REL"
[ -f "$SUMS" ] || fail "checksum file missing: $SUMS"

printf 'BASE1 PREVIEW VERIFY\n'
printf 'bundle : %s\n' "$BUNDLE_DIR"
printf 'input  : %s\n' "$SUMS_REL"
printf 'mode   : read-only\n'
printf '\n'

while IFS= read -r line || [ -n "$line" ]; do
  [ -n "$line" ] || continue
  set -- $line
  expected=${1:-}
  rel=${2:-}

  if [ -z "$expected" ] || [ -z "$rel" ]; then
    fail_check "invalid checksum entry: $line"
    continue
  fi

  file="$BUNDLE_DIR/$rel"
  if [ ! -f "$file" ]; then
    fail_check "listed file missing: $rel"
    continue
  fi

  actual=$(hash_file "$file")
  CHECKED=$((CHECKED + 1))
  if [ "$actual" = "$expected" ]; then
    pass_check "sha256 ok: $rel"
  else
    fail_check "checksum mismatch: $rel"
    printf 'expected: %s\n' "$expected"
    printf 'actual  : %s\n' "$actual"
  fi
done < "$SUMS"

if [ "$CHECKED" -eq 0 ]; then
  fail_check 'no checksum entries were checked'
fi

printf '\nchecked: %s\n' "$CHECKED"
printf 'result: %s\n' "$STATUS"
printf 'non-claims: no emulator launched; no installer run; no hardware validation; no bootable Base1 release claim\n'

case "$STATUS" in
  failed) exit 1 ;;
  *) exit 0 ;;
esac
