#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACTIVE = "edge/stable"
BASE = "base/v4.2.0"
VERSION = "v4.3.0-dev"

def upsert(path, title, body):
    p = ROOT / path
    old = p.read_text() if p.exists() else ""
    marker_start = f"<!-- phase1:auto:{title}:start -->"
    marker_end = f"<!-- phase1:auto:{title}:end -->"
    block = f"{marker_start}\n{body.rstrip()}\n{marker_end}\n"
    if marker_start in old and marker_end in old:
        before = old.split(marker_start)[0]
        after = old.split(marker_end, 1)[1].lstrip("\n")
        p.write_text(before + block + "\n" + after)
    else:
        prefix = old.rstrip() + "\n\n" if old.strip() else ""
        p.write_text(prefix + block)

repo_body = f"""## Phase1 repository model

- `{BASE}` is the frozen stable base.
- `{ACTIVE}` is the active default development path.
- `checkpoint/*` branches are verified milestone snapshots.
- `feature/*` branches target `{ACTIVE}`.

Keep the 4.2.0 image and stable base boring. Move tested work through edge/stable.
"""

current_body = f"""## Current development status

- Current edge version: `{VERSION}`
- Stable base: `{BASE}`
- Active path: `{ACTIVE}`
- Docs are generated by `scripts/update-docs.py`.
"""

upsert("README.md", "repo-model", repo_body)
upsert("README.md", "current-status", current_body)
upsert("REPO_DOCTRINE.md", "repo-model", repo_body)
upsert("EDGE_STABLE_CHECKPOINT.md", "current-status", current_body)
upsert("FEATURE_STATUS.md", "repo-model", repo_body)
upsert("EDGE.md", "repo-model", repo_body)
upsert("WIKI_ROADMAP.md", "repo-model", repo_body)

wiki = ROOT / "docs" / "wiki"
wiki.mkdir(parents=True, exist_ok=True)
upsert("docs/wiki/Repository-Model.md", "repo-model", repo_body)
upsert("docs/wiki/Current-Status.md", "current-status", current_body)

print("docs: synchronized README, docs, and wiki metadata")
print(f"docs: preserved stable base {BASE}")
print(f"docs: active path {ACTIVE}")
