#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACTIVE = "edge/stable"
BASE = "base/v6.0.0"
VERSION = "v7.0.1"


def upsert(path, title, body):
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    old = p.read_text() if p.exists() else ""
    marker_start = f"<!-- phase1:auto:{title}:start -->"
    marker_end = f"<!-- phase1:auto:{title}:end -->"
    block = f"{marker_start}\n{body.rstrip()}\n{marker_end}\n"
    if marker_start in old and marker_end in old:
        before = old.split(marker_start)[0]
        after = old.split(marker_end, 1)[1].lstrip("\n")
        p.write_text(before + block + "\n" + after)
    else:
        prefix = old.rstrip() + "\n\n" if old.strip() else ""
        p.write_text(prefix + block)


repo_body = f"""## Phase1 repository model

- `{BASE}` is the current stable base.
- `{ACTIVE}` is the active default development path.
- `checkpoint/*` branches are verified milestone snapshots.
- `feature/*` branches target `{ACTIVE}`.

Keep stable bases boring. Move tested work through edge/stable.
"""

current_body = f"""## Current development status

- Current edge version: `{VERSION}`
- Stable base: `{BASE}`
- Active path: `{ACTIVE}`
- Docs are generated by `scripts/update-docs.py`.
"""

# Keep generated documentation inside tracked documentation surfaces. Do not
# recreate old root-level generated notes such as EDGE.md, FEATURE_STATUS.md,
# REPO_DOCTRINE.md, EDGE_STABLE_CHECKPOINT.md, or WIKI_ROADMAP.md.
upsert("README.md", "repo-model", repo_body)
upsert("README.md", "current-status", current_body)

upsert("docs/repo/EDGE.md", "repo-model", repo_body)
upsert("docs/wiki/Repository-Model.md", "repo-model", repo_body)
upsert("docs/wiki/Current-Status.md", "current-status", current_body)

print("docs: synchronized README and tracked docs/wiki metadata")
print(f"docs: stable base {BASE}")
print(f"docs: active path {ACTIVE}")
print("docs: root-level generated notes are intentionally not created")
