pub fn get_man_page(cmd: &str) -> Option<String> {
    let page = match cmd {
        "help" => "help: list commands\nUsage: help",
        "man" => "man: show a manual page\nUsage: man <command>",
        "ps" => "ps: show simulated process table\nUsage: ps",
        "top" => "top: show simulated scheduler state\nUsage: top",
        "kill" => "kill: terminate a simulated process\nUsage: kill <pid>",
        "nice" => "nice: set simulated process priority (-20..19)\nUsage: nice <pid> <priority>",
        "spawn" => "spawn: create a simulated process\nUsage: spawn <name> [args...] [--background]",
        "jobs" => "jobs: list simulated background jobs\nUsage: jobs",
        "fg" => "fg: move a simulated job to foreground\nUsage: fg <pid>",
        "bg" => "bg: move a simulated job to background\nUsage: bg <pid>",
        "ls" => "ls: list VFS directory contents\nUsage: ls [-l] [path]",
        "cd" => "cd: change VFS working directory\nUsage: cd [directory]",
        "pwd" => "pwd: print VFS working directory\nUsage: pwd",
        "cat" => "cat: read VFS file\nUsage: cat <file>",
        "mkdir" => "mkdir: create VFS directory\nUsage: mkdir <dir>",
        "touch" => "touch: create VFS file\nUsage: touch <file>",
        "rm" => "rm: remove VFS node\nUsage: rm <path>",
        "cp" => "cp: copy VFS file\nUsage: cp <src> <dst>",
        "mv" => "mv: move or rename VFS node\nUsage: mv <src> <dst>",
        "echo" => "echo: print text or redirect to a VFS file\nUsage: echo <text> [> file | >> file]",
        "env" => "env: print shell environment\nUsage: env",
        "export" => "export: set environment variable\nUsage: export VAR=value",
        "unset" => "unset: remove environment variable\nUsage: unset VAR",
        "python" | "py" => "python: run Python from a VFS file or inline code with timeout\nUsage: python <file.py> | python -c \"code\"",
        "plugin" | "plugins" => "plugins: list Python plugins in ./plugins\nRun a plugin by typing its command name.",
        "ned" | "nano" | "vi" => "ned: small line editor backed by the VFS\nUsage: ned <file>",
        "gcc" | "cc" => "gcc: compile and run C from VFS or inline code using host gcc/clang with timeout\nUsage: gcc <file.c> | gcc \"code\"",
        "browser" => "browser: fetch and render HTTP/HTTPS page text using curl\nUsage: browser <url> | browser phase1 | browser about",
        "ifconfig" => "ifconfig: show discovered host network interfaces\nUsage: ifconfig",
        "iwconfig" => "iwconfig: show WiFi information where available\nUsage: iwconfig",
        "wifi-scan" => "wifi-scan: list nearby WiFi networks using host tools\nUsage: wifi-scan",
        "wifi-connect" => "wifi-connect: dry-run by default; set PHASE1_ALLOW_HOST_NETWORK_CHANGES=1 to allow real host changes\nUsage: wifi-connect <ssid> [password]",
        "ping" => "ping: run bounded host ping\nUsage: ping <host>",
        "nmcli" => "nmcli: show NetworkManager state on Linux\nUsage: nmcli",
        "lspci" => "lspci: list simulated PCIe devices\nUsage: lspci",
        "pcie" => "pcie: show PCIe subsystem summary\nUsage: pcie",
        "cr3" => "cr3: show simulated CR3 value\nUsage: cr3",
        "loadcr3" => "loadcr3: load simulated CR3 value; alignment is checked unless PCIDE is enabled\nUsage: loadcr3 <hex|decimal>",
        "cr4" => "cr4: show simulated CR4 flags\nUsage: cr4",
        "pcide" => "pcide: toggle simulated CR4.PCIDE\nUsage: pcide on|off",
        "free" | "mem" => "free: show simulated memory information\nUsage: free",
        "df" => "df: show simulated VFS capacity\nUsage: df",
        "whoami" => "whoami: print current simulated user\nUsage: whoami",
        "id" => "id: print simulated user id\nUsage: id",
        "su" => "su: switch simulated user\nUsage: su <user>",
        "dmesg" => "dmesg: show simulated boot messages\nUsage: dmesg",
        "vmstat" => "vmstat: show simulated memory/process stats\nUsage: vmstat",
        "history" => "history: show shell command history\nUsage: history",
        "uname" => "uname: show simulator kernel identity\nUsage: uname",
        "date" => "date: show host UNIX timestamp\nUsage: date",
        "uptime" => "uptime: show simulator uptime\nUsage: uptime",
        "hostname" => "hostname: show virtual hostname\nUsage: hostname",
        "sandbox" | "nsinfo" => "sandbox: show safety model\nUsage: sandbox",
        "version" => "version: show phase1 version\nUsage: version",
        "tree" => "tree: recursively display the VFS\nUsage: tree",
        "clear" => "clear: clear terminal\nUsage: clear",
        "exit" | "quit" | "shutdown" | "poweroff" => "exit: terminate simulator\nUsage: exit",
        _ => return None,
    };

    Some(page.to_string())
}
